### ISSUE TITLE
NullPointerException in the game runner with the sample Python3 bot

### ISSUE THREAD

**Issue by mdkozlowski** [EntelectChallenge/2019-Worms#3]
```Reading config file: ./game-runner-config.json
No match id found. Generating one
Building game name
Player A id not found. Generating one
Player B id not found. Generating one
Match will be running with a seed of: 4263
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
./reference-bot/javascript
./reference-bot/javascript/
./starter-bots/python3
java.lang.NullPointerException
java.lang.NullPointerException
	at za.co.entelect.challenge.botrunners.BotRunnerFactory.createBotRunner(BotRunnerFactory.java:8)
	at za.co.entelect.challenge.player.bootstrapper.PlayerBootstrapper.parsePlayer(PlayerBootstrapper.java:73)
	at za.co.entelect.challenge.player.bootstrapper.PlayerBootstrapper.parsePlayer(PlayerBootstrapper.java:61)
	at za.co.entelect.challenge.player.bootstrapper.PlayerBootstrapper.loadPlayers(PlayerBootstrapper.java:53)
	at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.run(GameBootstrapper.java:57)
	at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.main(GameBootstrapper.java:38)
```
Javascript and java sample bots run fine. From what I can tell the python bot doesn't launch at all
The engine used is the build from the starter pack release
I'm using Python 3.7 with conda and openjdk 1.8 on Ubuntu 18.10

**Comment by RohanChhipa** [comment]
Hi,

We have made a fix for this, it is currently in review and will release it with the next starter pack. As a workaround, for now, you can simply change the `botLanguage` in the bot.json file from `python3` to `python` and you'll be able to run the python bot.
